base_url = "https://iotmq.io"
default_language = "en"

[languages.en]
title = "IoTMQ"
description = "Rust MQTT"

[languages.zh]
title = "IoTMQ中文"
description = "高性能纯 Rust MQTT 消息服务器"
build_search_index = true

[languages.zh.translations]
toc = "本页目录"
get_started = "快速上手"

[languages.en.translations]
toc = "on this page"
get_started = "Get Started"

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
is_dev = true
languages = [
    { code = "en", name = "English" },
    { code = "zh", name = "简体中文" }
]
versions = []